apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-list
  namespace: todo-list
spec:
  schedule: "0 21 * * *" # 日本時間で毎日6時に実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-list
            image: ghcr.io/a-takamin/todo-list:latest
            envFrom:
            - secretRef:
                name: todo-list-secret
          restartPolicy: OnFailure
